const courses={
  'full-stack':{name:'Full Stack Development',category:'Technical program',duration:'16 weeks',level:'Beginner friendly',format:'Live + projects',art:'</>',theme:'linear-gradient(135deg,#163a4a,#2d6c77)',summary:'Design, build and deploy complete web experiences with the tools and workflows used by modern development teams.',overview:'Build confidence across the full web-development lifecycle. You will learn through guided lessons, practical labs and portfolio-ready projects.',learn:['Create responsive interfaces with HTML, CSS and JavaScript','Build APIs and data-driven applications','Use Git, deployment tools and modern developer workflows','Complete projects that demonstrate your skills to employers']},
  'digital-marketing':{name:'Digital Marketing',category:'Business & creative program',duration:'12 weeks',level:'Live projects',format:'Live + projects',art:'◎',theme:'linear-gradient(135deg,#7c3f24,#da8150)',summary:'Grow brands with strategy, content and performance marketing that reaches the right audience.',overview:'Learn how to plan, launch and measure campaigns across the channels businesses use every day.',learn:['Plan audience-led marketing strategies','Create social, search and content campaigns','Measure performance with practical analytics','Build a campaign portfolio with live-project experience']},
  'cyber-security':{name:'Cyber Security',category:'Technical program',duration:'14 weeks',level:'Hands-on labs',format:'Live + labs',art:'◈',theme:'linear-gradient(135deg,#062c39,#198657)',summary:'Defend systems and gain in-demand security skills through practical labs and real-world scenarios.',overview:'Develop a strong security mindset while exploring the methods, tools and processes used to protect digital systems.',learn:['Understand networks, threats and security fundamentals','Practice ethical hacking in safe lab environments','Identify and respond to common security risks','Build a job-ready cyber-security skills portfolio']},
  'data-science-ai':{name:'Data Science & AI',category:'Technical program',duration:'18 weeks',level:'Portfolio ready',format:'Live + projects',art:'AI',theme:'linear-gradient(135deg,#302560,#7561be)',summary:'Turn data into smart decisions and build intelligent solutions for tomorrow’s workplace.',overview:'Learn to work with data from first exploration to useful models, with hands-on projects that make your portfolio stand out.',learn:['Prepare, explore and visualise meaningful data','Use Python for practical data analysis','Understand machine-learning foundations','Create AI-powered projects with clear business value']},
  'ui-ux-design':{name:'UI/UX Design',category:'Business & creative program',duration:'12 weeks',level:'Beginner friendly',format:'Live + projects',art:'✦',theme:'linear-gradient(135deg,#693268,#d479a0)',summary:'Design intuitive, polished digital experiences for real people.',overview:'Learn a user-centred design process and turn ideas into clear, testable digital product experiences.',learn:['Research users and define practical problems','Create flows, wireframes and interface designs','Build prototypes that communicate your ideas','Present a polished case-study portfolio']},
  'business-analytics':{name:'Business Analytics',category:'Business & creative program',duration:'10 weeks',level:'Beginner friendly',format:'Live + projects',art:'↗',theme:'linear-gradient(135deg,#274d46,#80a967)',summary:'Use data, dashboards and strategy to make better business decisions.',overview:'Learn to turn business questions into useful analysis, reports and recommendations that people can act on.',learn:['Structure business questions with data in mind','Build clear reports and dashboards','Interpret trends and communicate insight','Use practical analysis tools with confidence']}
};
const course=courses[new URLSearchParams(location.search).get('course')]||courses['full-stack'];
document.title=`${course.name} | Brunda's Academy`;
const learningItems=course.learn.map(item=>`<li>${item}</li>`).join('');
document.querySelector('#course-details').innerHTML=`<section class="course-hero"><div><p class="course-label">${course.category}</p><h1>${course.name.replace(' & ',' &<br>')}<br><em>starts here.</em></h1><p class="course-summary">${course.summary}</p><a class="btn btn-primary" href="index.html#contact">Enquire about this course <span>→</span></a><div class="course-facts"><div><small>Duration</small><b>${course.duration}</b></div><div><small>Level</small><b>${course.level}</b></div><div><small>Format</small><b>${course.format}</b></div></div></div><div class="course-art" style="background:${course.theme}">${course.art}</div></section><section class="course-body"><div><h2>What you’ll learn</h2><p>${course.overview}</p><ul class="learning-list">${learningItems}</ul></div><aside class="course-enquire"><h2>Ready to take the next step?</h2><p>Talk to an advisor about the next cohort, schedule and course fit.</p><a class="btn btn-primary" href="index.html#contact">Talk to an advisor <span>→</span></a></aside></section>`;
